services:
  demo-app:
    build: 
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - dockervenv_api:/src/.venv
      - ./api:/src
      # - .:/src
    ports:
      - 8000:8000 #ホストの8000ポートをコンテナの8000ポートに
    environment:
      - WATCHFILES_FORCE_POLLING=true 
    tty: true
    depends_on:
      - db
    
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
      TZ: 'Asia/Tokyo'
      tty: true
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    

  web:
      build: 
        context: ./web
        dockerfile: Dockerfile
      volumes:
        - ./web/taskapp-web:/app
        - /app/node_modules
        # - .dockervenv:/src/web/.venv
        # - .:/src
      ports:
        - 5173:5173 
      environment:
        - WATCHFILES_FORCE_POLLING=true 
      tty: true
      depends_on:
        - db
    

volumes:
  dockervenv_api:
    driver: local
  postgres_data:
    driver: local
  web_data:
    driver: local



